spring:
  datasource:
    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
    url: jdbc:h2:~/test  # H2 접속 정보
    username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
    password:  # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)



  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  profiles:
    include: jwt

  h2:
    console:
      enabled: true
      path: /console

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB

server:
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/css,application/javascript,application/json, application/zip, application/octet-stream


